---
title: "Untitled"
output: html_document
---


```{r}


library(readxl)
nanostring_scores <- read_excel("C:/Users/elif/Desktop/nanostring_scores.xlsx")
View(nanostring_scores)

nanostring_Scores_2 <- read_excel("C:/Users/elif/Desktop/nanostring_Scores_2.xlsx")
View(nanostring_Scores_2)
dim(nanostring_Scores_2)

cartridge_patient

row_name<-nanostring_Scores_2$...1
nanostring_Scores_2<-nanostring_Scores_2[,-1]
row.names(nanostring_Scores_2)<-row_name
nanostring_Scores_2<-t(nanostring_Scores_2)


dim(cartridge)


cartridge<-cartridge_patient[-c(97,98,208,209,210),]


data<-cbind(cartridge, nanostring_Scores_2)
data<-data[,-(1:2)]

names(data)[3]<-paste("OS")
names(data)[4]<-paste("OS01")
names(data)[5]<-paste("RFS")
names(data)[6]<-paste("RFS01")
names(data)[12]<-paste("cutoff")
names(data)[18]<-paste("z_score")
names(data)[20]<-paste("z_score_fit")

names(data)[15]<-paste("percentile_score")
names(data)[19]<-paste("z_score_low_removed")
names(data)[13]<-paste("cutoff_low_removed")
names(data)[14]<-paste("cutoff_fit")
names(data)[16]<-paste("percentile_score_low_removed")
names(data)[17]<-paste("percentile_score_fit")


library(readr)
expression_data <- read_delim("C:/Users/elif/Desktop/Stage2, LMU, normalized data, Nanostring, whole cohort, 18.03.2022.txt", 
    delim = "\t", escape_double = FALSE, 
    trim_ws = TRUE)
expression_data<-expression_data[-1,-c(2:19)]
probe<-expression_data$`Probe Name`
expression_data<-expression_data[,-1]
row.names(expression_data)<-probe
expression_data<-t(expression_data)
expression_data<-expression_data[-c(97,98,146,208,209),]
dim(expression_data)

data_2<-cbind(data, expression_data)

km_fit<-survfit(Surv(RFS,RFS01) ~ cutoff , data = data_2)
plot(km_fit)
ggsurvplot(km_fit, pval = TRUE, data=data_2)


survfit(Surv(RFS,RFS01)~cutoff, data_2)
coxph(Surv(RFS, RFS01) ~ cutoff, data = data_2)

coxph(Surv(RFS, RFS01) ~ cutoff_score_low_removed, data = data_2)

##
coxph(Surv(RFS, RFS01) ~ cutoff_fit, data = data_2)



coxph(Surv(RFS, RFS01) ~ percentile_score, data = data_2)


coxph(Surv(RFS, RFS01) ~ percentile_score_low_removed, data = data_2)

##
coxph(Surv(RFS, RFS01) ~ percentile_score_fit, data = data_2)




coxph(Surv(RFS, RFS01) ~ z_score, data = data_2)

coxph(Surv(RFS, RFS01) ~ z_score_low_removed, data = data_2)

##
coxph(Surv(RFS, RFS01) ~ z_score_fit, data = data_2)

```

```{r, fig.height=5, fig.width=5}


library(survminer)
library("survival")
library(MASS)
library(data.table)
library(ggplot2)

data<-data[,-(1:2)]
data[,10:18]<-sapply(data[,10:18],as.numeric)
str(nano_data)


genes <- "cutoff_low_removed"

cutoff <- surv_cutpoint(data, time = "RFS", event = "RFS01", variables = genes, minprop = 0.1, progressbar = TRUE)
surv_cat <- surv_categorize(cutoff)
#single genes p-value
#formulafinal <- list (Surv(RFS, RFS01) ~ ITGB1)
formulafinal <- list(paste("Surv(RFS, RFS01) ~ ", genes))
fit <- surv_fit(eval(parse(text=formulafinal)), data = surv_cat)
fit
pvalue <- surv_pvalue(fit)
#calculate HR
univ_formulas <- sapply(genes, function(x) as.formula(paste('Surv(RFS, RFS01)~', x)))
univ_models <- lapply(univ_formulas, function(x){coxph(x, data = surv_cat)})
# Extract data 
univ_results <- lapply(univ_models,
                       function(x){ 
                         x <- summary(x)
                         p.value<-signif(x$wald["pvalue"], digits=4)
                         wald.test<-signif(x$wald["test"], digits=4)
                         beta<-signif(x$coef[1], digits=4);#coeficient beta
                         HR <-signif(x$coef[2], digits=4);#exp(beta)
                         HR.confint.lower <- signif(x$conf.int[,"lower .95"], 4)
                         HR.confint.upper <- signif(x$conf.int[,"upper .95"],4)
                         'HR <- paste0(HR, " (", 
                                      HR.confint.lower, "-", HR.confint.upper, ")")'
                         res<-c(beta, 1/HR, 1/HR.confint.upper, 1/HR.confint.lower, wald.test, p.value)
                         names(res)<-c("beta", "HR","95% CI lower", "95% CI upper", "wald.test", 
                                       "p.value")
                         return(res)
                         #return(exp(cbind(coef(x),confint(x))))
                       })
res <- t(as.data.frame(univ_results, check.names = FALSE))


pvalonly <- pvalue$pval
pvaldigit <- formatC(pvalonly, digits=3)
res_x <- as.data.frame(res)
HR <- res_x$HR
HRdigit<-formatC(HR, digits = 3)


cutoff_plot<-ggsurvplot(fit, pval= FALSE,data = data,palette = c("brown2", "blue3"), risk.table =FALSE,legend = "top", 
           legend.title = "",
           font.legend = 15,
           legend.labs=c("High","Low"),
           ylab = "Relapse Free Survival (%)",
           xlab = "Time (years)",
           font.main = 10,
           font.x =  14,
           font.y = 14,
           font.tickslab = 13,
           tables.height = 0.25,
           conf.int = TRUE,
           conf.int.alpha=0.2
           )

cutoff_plot$plot<- cutoff_plot$plot+theme(axis.title.y = element_text(margin = margin(r = 20), face = "bold"), plot.title = element_text(hjust = 0.5,size = 18  ,face = "bold"),axis.title.x=element_text(face="bold", margin = margin(t=20)))


cutoff_plot$plot<-cutoff_plot$plot+
  ggplot2::annotate("text",
    x= 0, y=0.1,
    vjust = "inward", hjust = "inward",
    label = paste("HR = ", HRdigit, "\np =", pvaldigit),
    size = 5,
    fontface="bold"
  )

cutoff_plot  

```

```{r, fig.height=5.5, fig.width=5}
library(readxl)
expression_data<- read_excel("C:/Users/elif/Desktop/nanostring_Stage II_results/normalized_expression_counts_wo_flags.xlsx")
expression_data<-expression_data[-(1:2),]
probe<-expression_data$`Probe Name`
expression_data<-expression_data[,-1]
row.names(expression_data)<-probe
expression_data<-t(expression_data)
expression_data<-expression_data[-(206:223),]

names(solver_data)[5]<-paste("RFS")
names(solver_data)[6]<-paste("RFS01")

nano_data<-cbind(data,expression_data)
nano_data<-nano_data[,-(12:20)]

gene <- read.delim("survival_analysis_nanostring/genes.txt", check.names=FALSE, stringsAsFactors=FALSE)

genes <- gene$Name

nano_data<-nano_data[,-(1:2)]
nano_data[,10:90]<-sapply(nano_data[,10:90],as.numeric)
str(nano_data)




names(nano_data)[9]<-paste("KRAS_mutation")
names(nano_data)[6]<-paste("Sex")
names(nano_data)[5]<-paste("Age")
names(nano_data)[7]<-paste("Grade")


genes <- "BACE1"


cutoff <- surv_cutpoint(nano_data, time = "OS", event = "OS01", variables = genes, minprop = 0.1, progressbar = TRUE)

surv_cat <- surv_categorize(cutoff)

formulafinal <- list(paste("Surv(OS, OS01) ~ ", genes))
fit <- surv_fit(eval(parse(text=formulafinal)), data = surv_cat)
pvalue <- surv_pvalue(fit)
#calculate HR
univ_formulas <- sapply(genes, function(x) as.formula(paste('Surv(OS, OS01)~', x)))
univ_models <- lapply(univ_formulas, function(x){coxph(x, data = surv_cat)})
# Extract data 
univ_results <- lapply(univ_models,
                       function(x){ 
                         x <- summary(x)
                         p.value<-signif(x$wald["pvalue"], digits=4)
                         wald.test<-signif(x$wald["test"], digits=4)
                         beta<-signif(x$coef[1], digits=4);#coeficient beta
                         HR <-signif(x$coef[2], digits=4);#exp(beta)
                         HR.confint.lower <- signif(x$conf.int[,"lower .95"], 4)
                         HR.confint.upper <- signif(x$conf.int[,"upper .95"],4)
                         'HR <- paste0(HR, " (", 
                                      HR.confint.lower, "-", HR.confint.upper, ")")'
                         res<-c(beta, 1/HR, 1/HR.confint.upper, 1/HR.confint.lower, wald.test, p.value)
                         names(res)<-c("beta", "HR","95% CI lower", "95% CI upper", "wald.test", 
                                       "p.value")
                         return(res)
                         #return(exp(cbind(coef(x),confint(x))))
                       })
res <- t(as.data.frame(univ_results, check.names = FALSE))



pvalonly <- pvalue$pval
pvaldigit <- formatC(pvalonly, digits=3)
res_x <- as.data.frame(res)
HR <- res_x$HR
HRdigit<-formatC(HR, digits = 3)

#ggsurvplot(fit=fit, pval=TRUE)

ggsurv <- ggsurvplot(fit = fit, pval = FALSE, 
           risk.table = FALSE,
           palette = c("brown2", "blue3"),
           legend = "top", 
           #legend = c(0.8, 0.5),
           legend.title = "",
           legend.labs = c("High", "Low"), # Change legend labels
           font.legend = 15,
           xlab = "Time (years)",   # customize X axis label
           ylab = "Overall Survival (%)",   # customize X axis label
           #break.time.by = 20,     # break X axis in time intervals by 20.
           font.main = 14,
           font.x =  14,
           font.y = 14,
           font.tickslab = 13,
           tables.height = 0.20,
           conf.int = TRUE,
           conf.int.alpha=0.2,
           title="BACE1"
           )

ggsurv$plot <- ggsurv$plot + theme(axis.title.y = element_text(margin = margin(r = 20), face = "bold"), plot.title = element_text(hjust = 0.5,size = 18  ,face = "bold",margin = margin(b=20)),axis.title.x=element_text(face="bold", margin = margin(t=20))) #decrease the distance between y-axis title and the axis


ggsurv$plot <- ggsurv$plot +
  ggplot2::annotate(
    "text",
    x= 0, y=0,
    vjust = "inward", hjust = "inward",
    label = paste("HR = ", HRdigit, "\np =", pvaldigit),
    size = 5,
    fontface="bold"
  )



ggsurv

```





```{r}

## GRAD

#169, 201 ,204
filter(nano_data$Grade=="1")

nano_2<-nano_data%>%
  filter(Grade>1)
grad_2<-survfit(Surv(RFS,RFS01)~Grade, data = nano_2)
surv_pvalue(grad_2)
ggsurvplot(grad_2, pval = TRUE)


ggsurvplot(grad_fit, pval = TRUE)
grad_fit<-survfit(Surv(RFS,RFS01)~Grade, data = nano_data)
surv_pvalue(grad_fit)
grad_plot<-ggsurvplot(grad_fit, pval= FALSE,data = nano_data,palette = c("brown2", "blue3","darkgreen"), risk.table = TRUE,legend = "top", 
           legend.title = "",
           legend.labs = c("Grade 1", "Grade 2","Grade 3"),
           font.legend = 10,
           ylab = "Relapse Free Survival (%)",
           xlab = "Time (years)",
           font.main = 10,
           font.x =  10,
           font.y = 10,
           font.tickslab = 10,
           tables.height = 0.40
           )

grad_plot$plot<- grad_plot$plot+theme(axis.title.y = element_text(margin = margin(r = 0), face = "bold"), plot.title = element_text(hjust = 0.5,size = 18  ,face = "bold"))

grad_plot$plot<-grad_plot$plot+
  ggplot2::annotate("text",
    x= 0, y=0.1,
    vjust = "inward", hjust = "inward",
   label = paste("p = 0.023"),
    size = 4,
    fontface="bold"
  )

grad_plot  
```

```{r}

##SEX

sex_fit<-survfit(Surv(RFS,RFS01)~Sex, data = nano_data)
surv_pvalue(sex_fit)
sex_plot<-ggsurvplot(sex_fit, pval= FALSE,data = nano_data,palette = c("brown2", "blue3"), risk.table = TRUE,legend = "top", 
           legend.title = "",
           legend.labs = c("Male", "Female"),
           font.legend = 10,
           ylab = "Relapse Free Survival (%)",
           xlab = "Time (years)",
           font.main = 10,
           font.x =  10,
           font.y = 10,
           font.tickslab = 10,
           tables.height = 0.35
           )

sex_plot$plot<- sex_plot$plot+theme(axis.title.y = element_text(margin = margin(r = 0), face = "bold"), plot.title = element_text(hjust = 0.5,size = 18  ,face = "bold"))

sex_plot$plot<-sex_plot$plot+
  ggplot2::annotate("text",
    x= 0, y=0.1,
    vjust = "inward", hjust = "inward",
    label = paste("p = 0.98"),
    size = 4,
    fontface="bold"
  )

sex_plot  
```

```{r}
##pT
ggsurvplot(pt_fit, pval = TRUE)
pt_fit<-survfit(Surv(RFS,RFS01)~T, data = nano_data)
surv_pvalue(pt_fit)
summary(pt_fit)
pt_plot<-ggsurvplot(pt_fit, pval= FALSE,data = nano_data,palette = c("brown2", "blue3"), risk.table = "percentage",legend = "top", 
           legend.title = "",
           legend.labs = c("T3", "T4"),
           font.legend = 10,
           ylab = "Relapse Free Survival (%)",
           xlab = "Time (years)",
           font.main = 10,
           font.x =  10,
           font.y = 10,
           font.tickslab = 10,
           tables.height = 0.35
           )

pt_plot$plot<- pt_plot$plot+theme(axis.title.y = element_text(margin = margin(r = 20), face = "bold"), plot.title = element_text(hjust = 0.5,size = 18  ,face = "bold"))

pt_plot$plot<-pt_plot$plot+
  ggplot2::annotate("text",
    x= 0, y=0.1,
    vjust = "inward", hjust = "inward",
    label = paste("p < 0.0001"),
    size = 4,
    fontface="bold"
  )
summary(pt_plot)
summarise(pt_fit)
pt_plot  
```

```{r}
##mutation

mut_fit<-survfit(Surv(RFS,RFS01)~KRAS_mutation, data = nano_data)
mut_plot<-ggsurvplot(mut_fit, pval= FALSE,data = nano_data,palette = c("brown2", "blue3"), risk.table = TRUE,legend = "top", 
           legend.title = "",
           legend.labs = c("KRAS mut.", "no KRAS mut."),
           font.legend = 10,
           ylab = "Relapse Free Survival (%)",
           xlab = "Time (years)",
           font.main = 10,
           font.x =  10,
           font.y = 10,
           font.tickslab = 10,
           tables.height = 0.35
           )

mut_plot$plot<- mut_plot$plot+theme(axis.title.y = element_text(margin = margin(r = -70), face = "bold"), plot.title = element_text(hjust = 0.5,size = 18  ,face = "bold"))

mut_plot$plot<-mut_plot$plot+
  ggplot2::annotate("text",
    x= 0, y=0.1,
    vjust = "inward", hjust = "inward",
    label = paste("p = 0.44"),
    size = 4,
    fontface="bold"
  )

mut_plot  
```

```{r}
##AGE


age_fit<-survfit(Surv(RFS,RFS01)~(Age<55), data = nano_data)
surv_pvalue(age_fit)
age_plot<-ggsurvplot(age_fit, pval= FALSE,data = nano_data,palette = c("brown2", "blue3"), risk.table = TRUE,legend = "top", 
           legend.title = "",
           legend.labs = c("Age<55", "Age>=55"),
           font.legend = 10,
           ylab = "Relapse Free Survival (%)",
           xlab = "Time (years)",
           font.main = 10,
           font.x =  10,
           font.y = 10,
           font.tickslab = 10,
           tables.height = 0.35
           )

age_plot$plot<- age_plot$plot+theme(axis.title.y = element_text(margin = margin(r = -20), face = "bold"), plot.title = element_text(hjust = 0.5,size = 18  ,face = "bold"))

age_plot$plot<-age_plot$plot+
  ggplot2::annotate("text",
    x= 0, y=0.1,
    vjust = "inward", hjust = "inward",
    label = paste("p = 0.0073"),
    size = 4,
    fontface="bold"
  )

age_plot  
```


```{r}
install.packages("finalfit")
library(finalfit)
library(dplyr)
library(gtsummary)
View(nano_data)
explanatory = c(" T", "Grade", "KRAS_mutation" , "Age", "Sex")
dependent = "Surv(RFS, RFS01)"
nano_data %>%
    finalfit(dependent, explanatory)


explanatory = c(" T", "Grade", "KRAS_mutation" , "Age", "Sex")
dependent = "RFS01"
nano_data %>%
summary_factorlist(dependent, explanatory, p=TRUE, add_dependent_label=TRUE)



explanatory = c(" T", "Grade", "KRAS_mutation" , "Age", "Sex")
dependent = "Surv(RFS, RFS01)"
nano_data %>%
    finalfit(dependent, explanatory)



# Separate tables
nano_data %>%
    summary_factorlist(dependent, explanatory, fit_id=TRUE) -> example.summary
nano_data %>%
    glmuni(dependent, explanatory) %>%
    fit2df(estimate_suffix=" (univariable)") -> example.univariable
nano_data %>%
    glmmulti(dependent, explanatory) %>%
    fit2df(estimate_suffix=" (multivariable)") -> example.multivariable

# Pipe together
example.summary %>%
    finalfit_merge(example.univariable) %>%
    finalfit_merge(example.multivariable) %>%
    select(-c(fit_id, index)) %>% # remove unnecessary columns
    dependent_label(nano_data, dependent, prefix="") # place dependent variable label


### OR plot
explanatory = c("T", "Grade", "KRAS_mutation" , "Age", "Sex")
dependent = "RFS"
nano_data %>%
  or_plot(dependent, explanatory)
# Previously fitted models (`glmmulti()` or `glmmixed()`) can be provided directly to `glmfit`



# HR plot
nano_data %>%
  hr_plot(dependent, explanatory, dependent_label = "Survival")
# Previously fitted models (`coxphmulti`) can be provided directly using `coxfit`




####

mod1<- glm(RFS01~T+Grade+Sex+KRAS_mutation+Age, data = nano_data, family = "binomial")

mod1 %>%
  tbl_regression(exponentiate=TRUE )%>%
  bold_labels()%>%
  bold_p(t= 0.1)


fit_multi %>%
  tbl_regression(exponentiate=TRUE )%>%
  bold_labels()%>%
  bold_p(t= 0.1)

mod1 %>%
  tbl_regression(exponentiate = TRUE) %>%
  as_gt() %>%
  gt::tab_source_note(gt::md("*This data is simulated*"))



nano_data %>%
  select(RFS01, T, Grade, KRAS_mutation , Age, Sex) %>%
  tbl_uvregression(
    include = everything(),
    method = glm,
    y = RFS01,
    method.args = list(family = binomial),
    exponentiate = TRUE,
    pvalue_fun = ~style_pvalue(.x, digits = 2)
  ) %>%
  add_global_p() %>%  # add global p-value 
  add_nevent() %>%    # add number of events of the outcome
  add_q() %>%         # adjusts global p-values for multiple testing
  bold_p() %>%        # bold p-values under a given threshold (default 0.05)
  bold_p(t = 0.10, q = TRUE) %>% # now bold q-values under the threshold of 0.10
  bold_labels()


nano_data %>%
  select(RFS01, T, Grade, KRAS_mutation , Age, Sex) %>%
  tbl_summary(by=RFS01) %>%
  add_p() %>%
  add_overall()%>%
  add_n()%>%
  bold_labels()

  

```



```{r,fig.height=5, fig.width=5}


nano_data<-nano_data[,-(1:2)]
nano_data[,10:90]<-sapply(nano_data[,10:90],as.numeric)
str(nano_data)


##most significant genes


#ATPSCKMT
#BACE1
#BET1L
#VPS35L
#CD2BP2
#CD40LG
#TMEM86B
#TRIP10
#ZNF785


gene <- read.delim("survival_analysis_nanostring/genes.txt", check.names=FALSE, stringsAsFactors=FALSE)

genes <- "ZNF785"


cutoff <- surv_cutpoint(nano_data, time = "OS", event = "OS01", variables = genes, minprop = 0.1, progressbar = TRUE)

surv_cat <- surv_categorize(cutoff)

formulafinal <- list(paste("Surv(OS, OS01) ~ ", genes))
fit <- surv_fit(eval(parse(text=formulafinal)), data = surv_cat)
pvalue <- surv_pvalue(fit)
#calculate HR
univ_formulas <- sapply(genes, function(x) as.formula(paste('Surv(OS, OS01)~', x)))
univ_models <- lapply(univ_formulas, function(x){coxph(x, data = surv_cat)})
# Extract data 
univ_results <- lapply(univ_models,
                       function(x){ 
                         x <- summary(x)
                         p.value<-signif(x$wald["pvalue"], digits=4)
                         wald.test<-signif(x$wald["test"], digits=4)
                         beta<-signif(x$coef[1], digits=4);#coeficient beta
                         HR <-signif(x$coef[2], digits=4);#exp(beta)
                         HR.confint.lower <- signif(x$conf.int[,"lower .95"], 4)
                         HR.confint.upper <- signif(x$conf.int[,"upper .95"],4)
                         'HR <- paste0(HR, " (", 
                                      HR.confint.lower, "-", HR.confint.upper, ")")'
                         res<-c(beta, 1/HR, 1/HR.confint.upper, 1/HR.confint.lower, wald.test, p.value)
                         names(res)<-c("beta", "HR","95% CI lower", "95% CI upper", "wald.test", 
                                       "p.value")
                         return(res)
                         #return(exp(cbind(coef(x),confint(x))))
                       })
res <- t(as.data.frame(univ_results, check.names = FALSE))



pvalonly <- pvalue$pval
pvaldigit <- formatC(pvalonly, digits=3)
res_x <- as.data.frame(res)
HR <- res_x$HR
HRdigit<-formatC(HR, digits = 3)

#ggsurvplot(fit=fit, pval=TRUE)

ggsurv <- ggsurvplot(fit = fit, pval = FALSE, 
           risk.table = FALSE,
           palette = c("brown2", "blue3"),
           legend = "top", 
           #legend = c(0.8, 0.5),
           legend.title = "",
           legend.labs = c("score high", "score low"), # Change legend labels
           font.legend = 10,
           xlab = "Time (years)",   # customize X axis label
           ylab = "Overall Survival (%)",   # customize X axis label
           #break.time.by = 20,     # break X axis in time intervals by 20.
           font.main = 10,
           font.x =  10,
           font.y = 10,
           font.tickslab = 10,
           tables.height = 0.35,
           title="ZNF785",
           conf.int=TRUE,
           conf.int.alpha=0.2
           )

ggsurv$plot <- ggsurv$plot + theme(axis.title.y = element_text(margin = margin(r = 20), face = "bold"), plot.title = element_text(hjust = 0.5,size = 18  ,face = "bold")) #decrease the distance between y-axis title and the axis


ggsurv$plot <- ggsurv$plot +
  ggplot2::annotate(
    "text",
    x= 0, y=0,
    vjust = "inward", hjust = "inward",
    label = paste("HR = ", HRdigit, "\np =", pvaldigit),
    size = 4,
    fontface="bold"
  )



ggsurv

```



